### Get all books
GET http://localhost:8080/books
Accept: application/v1+json

### Get book by ID
GET http://localhost:8080/books/1
x-api-version: 1

### Add a new book
POST http://localhost:8080/v1/books
Content-Type: application/json

{
  "title": "Book Five",
  "author": "Author Five",
  "isbn": "ISBN Five",
  "price": 500
}

### Update a book
PUT http://localhost:8080/books/1?version=1
Content-Type: application/json

{
  "id":1,
  "title": "Updated Book One",
  "isbn": "Updated ISBN",
  "price": 150
}

### Delete a book
DELETE http://localhost:8080/books/1